// Mock data for the Maendeleo discovery UI kit.
window.MK_DATA = {
  categories: ["All", "Food", "Coffee", "Grocery", "Services", "Health"],
  places: [
    { id: "karibu", name: "Karibu Market", cat: "Grocery", price: "$$", dist: "0.4 mi", rating: 5, reviews: 214,
      blurb: "Neighbourhood grocer with fresh produce daily — open till 8pm.",
      hue: 140, open: true,
      tags: ["Fresh produce", "Open late", "Card accepted"] },
    { id: "tausi", name: "Tausi Café", cat: "Coffee", price: "$", dist: "1.2 mi", rating: 4, reviews: 88,
      blurb: "Cozy corner café with garden seating and single-origin beans.",
      hue: 35, open: true,
      tags: ["Garden seating", "Wi-Fi", "Vegan options"] },
    { id: "mwanga", name: "Mwanga Studio", cat: "Services", price: "$$$", dist: "2.1 mi", rating: 4, reviews: 41,
      blurb: "Photography & print studio. By appointment, weekends included.",
      hue: 200, open: false,
      tags: ["By appointment", "Prints", "Weekend"] },
    { id: "afya", name: "Afya Clinic", cat: "Health", price: "$$", dist: "0.9 mi", rating: 5, reviews: 132,
      blurb: "Family clinic offering same-day appointments and pharmacy.",
      hue: 165, open: true,
      tags: ["Same-day", "Pharmacy", "Family"] },
    { id: "jiko", name: "Jiko Kitchen", cat: "Food", price: "$$", dist: "1.6 mi", rating: 4, reviews: 176,
      blurb: "Home-style East African plates, generous portions, lively room.",
      hue: 18, open: true,
      tags: ["Dine-in", "Takeaway", "Halal"] },
  ],
  reviews: [
    { id: 1, name: "Amani Juma", when: "2 days ago", rating: 5,
      text: "Always fresh, friendly staff, and never a long queue. My go-to for the weekly shop." },
    { id: 2, name: "Zola Kimani", when: "1 week ago", rating: 4,
      text: "Great selection and fair prices. Wish they opened a little earlier on Sundays." },
    { id: 3, name: "Baraka Ngugi", when: "3 weeks ago", rating: 5,
      text: "The produce section is excellent — everything looked picked that morning." },
  ],
};
